# JVM & IDE
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mappings
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

# Core Parameters
wikihelper_version=2.17.1
mod_id=aoawikihelpermod
mod_name=AoAWikiHelper

## Dependencies
minecraft_version=1.21
mc_version_range=[1.21,)
neoforge_version=21.0.148
neoforge_version_range=[21.0.148,)
neoforge_loader_version_range=[3,)
aoa_version=5563875
aoa_version_range=[3.7.12,)
geckolib_version=4.5.7